apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  labels:
    app: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
      - name: swagger-ui
        image: swaggerapi/swagger-ui:v3.14.1
        ports:
        - containerPort: 8080
        env:
        - name: BASE_URL
          value: /swagger-fosps
        - name: API_URLS
          value: >-
            [
            {url:'https://raw.githubusercontent.com/Gravitate-Health/keycloak/main/openapi.yaml',name:'Keycloack API'},
            {url:'https://raw.githubusercontent.com/Gravitate-Health/focusing-manager/main/openapi.yaml',name:'Focusing Manager'}
            ]
        volumeMounts:
        - name: kc-swagger
          mountPath: /usr/share/nginx/html/openapis
      volumes:
        - name: kc-swagger
          configMap:
            name: kc-swagger
            items:
              - key: swagger
                path: kc-api-configmap.yaml
