apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  labels:
    app: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
      - name: swagger-ui
        image: swaggerapi/swagger-ui:v5.1.0
        ports:
        - containerPort: 8080
        env:
        - name: BASE_URL
          value: /swagger-fosps
        - name: API_URLS
          value: >-
            [
            {url:'https://raw.githubusercontent.com/Gravitate-Health/keycloak/main/openapi.yaml',name:'Keycloack API'},
            {url:'https://raw.githubusercontent.com/Gravitate-Health/focusing-manager/main/openapi.yaml',name:'Focusing Manager'},
            {url:'https://raw.githubusercontent.com/Gravitate-Health/focusing-service-test/master/openapi.yaml',name:'Lens Selector Service'},
            {url:'https://raw.githubusercontent.com/Gravitate-Health/preprocessing-service-test/main/openapi.yaml',name:'Preprocessor Service'},
            {url:'https://raw.githubusercontent.com/Gravitate-Health/terminology-service/main/openapi.yaml',name:'Terminology Service'}
            #{url:'https://raw.githubusercontent.com/Gravitate-Health/MedicationInfo/main/openapi.yaml',name:'Medication Information'},
            #{url:'https://raw.githubusercontent.com/Gravitate-Health/MedicationManagement/main/openapi.yaml',name:'Medication Management'}
            ]
        volumeMounts:
        - name: kc-swagger
          mountPath: /usr/share/nginx/html/openapis
      volumes:
        - name: kc-swagger
          configMap:
            name: kc-swagger
            items:
              - key: swagger
                path: kc-api-configmap.yaml
